// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqCDcD5jHKhB2WeNScfsYFaqU_SMjv3Gs',
    appId: '1:1063163612294:web:64ad516526c5b56eedd507',
    messagingSenderId: '1063163612294',
    projectId: 'sumquiz-3d54e',
    authDomain: 'sumquiz-3d54e.firebaseapp.com',
    storageBucket: 'sumquiz-3d54e.firebasestorage.app',
    measurementId: 'G-HEMEGYRGSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrbOH8ycFvKcIiyJ8vXnRvUQF2zBVVnso',
    appId: '1:1063163612294:android:c2eddda0afa793abedd507',
    messagingSenderId: '1063163612294',
    projectId: 'sumquiz-3d54e',
    storageBucket: 'sumquiz-3d54e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_2umFs5332dy8fiCvy3lHkHiVWztjA4',
    appId: '1:1063163612294:ios:e65161b2afad0e3bedd507',
    messagingSenderId: '1063163612294',
    projectId: 'sumquiz-3d54e',
    storageBucket: 'sumquiz-3d54e.firebasestorage.app',
    iosBundleId: 'com.sumquiz.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU_2umFs5332dy8fiCvy3lHkHiVWztjA4',
    appId: '1:1063163612294:ios:84a8828a5917135cedd507',
    messagingSenderId: '1063163612294',
    projectId: 'sumquiz-3d54e',
    storageBucket: 'sumquiz-3d54e.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqCDcD5jHKhB2WeNScfsYFaqU_SMjv3Gs',
    appId: '1:1063163612294:web:64ad516526c5b56eedd507',
    messagingSenderId: '1063163612294',
    projectId: 'sumquiz-3d54e',
    authDomain: 'sumquiz-3d54e.firebaseapp.com',
    storageBucket: 'sumquiz-3d54e.firebasestorage.app',
    measurementId: 'G-HEMEGYRGSL',
  );
}
